name: "Branch/Build t"
on:
  pull_request

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.filter.outputs.workflows }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            typescript:
              - 'src/**'
              - 'test/**'

  check-ts:
    needs: paths-filter
    if: needs.paths-filter.outputs.typescript == 'true'
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            cache: 'npm'
        - run: npm ci
        - run: npm run check:ts

  check-lint:
    needs: paths-filter
    if: needs.paths-filter.outputs.typescript == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - run: npm ci
      - run: npm run check:lint

  check-prettier:
    needs: paths-filter
    if: needs.paths-filter.outputs.typescript == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - run: npm ci
      - run: npm run check:prettier

  test:
    runs-on: ubuntu-latest
    needs: [check-ts, check-lint, check-prettier]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - run: npm ci
      - run: npm t
