name: "Branch/Build"

on:
  pull_request:
    paths:
      - 'src/**'
      - 'test/**'

jobs:
  check-ts:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            cache: 'npm'
        - run: npm ci
        - run: npm run check:ts

  check-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - run: npm ci
      - run: npm run check:lint

  check-prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - run: npm ci
      - run: npm run check:prettier

  test:
    runs-on: ubuntu-latest
    needs: [check-ts, check-lint, check-prettier]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - run: npm ci
      - run: npm t
