name: "Master/Publish Release"
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'test/**'
      - 'index.ts'
      - 'package.json'
      - 'package-lock.json'

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

# inherit from the build workflow
jobs:
  check-ts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - run: npm ci
      - run: npm run check:ts

  check-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - run: npm ci
      - run: npm run check:lint

  check-prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - run: npm ci
      - run: npm run check:prettier

  test:
    runs-on: ubuntu-latest
    needs: [ check-ts, check-lint, check-prettier ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - run: npm ci
      - run: npm t

  publish-release:
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - name: GH_TOKEN lookup
        if: env.GH_TOKEN == ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "GH_TOKEN=${GITHUB_TOKEN}" >> $GITHUB_ENV

      - name: code checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master
          token: ${{ env.GH_TOKEN }}

      - name: setup node
        uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org/

      - name: perform release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm i
          npm run build
          npx standard-version
          git push --follow-tags origin main
          npm publish --access public
